version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: azazel_postgres
    restart: always
    environment:
      POSTGRES_DB: mattermost
      POSTGRES_USER: mmuser
      POSTGRES_PASSWORD: securepassword
    volumes:
      - /opt/azazel/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - azazel_net

  vector:
    image: timberio/vector:0.37.0-alpine
    container_name: azazel_vector
    restart: always
    volumes:
      - /opt/azazel/config/vector.toml:/etc/vector/vector.toml
      - /opt/azazel/logs:/logs
      - /var/log/suricata:/var/log/suricata  # Suricataのログディレクトリをマウント
      - /opt/azazel/logs:/opt/azazel/logs    # OpenCanaryのログディレクトリをマウント      
    command: --config /etc/vector/vector.toml
    networks:
      - azazel_net

  opencanary:
    image: thinkst/opencanary:latest
    container_name: azazel_opencanary
    restart: always
    volumes:
      - /opt/azazel/config/opencanary.conf:/root/.opencanary.conf
      - /opt/azazel/logs:/logs
    ports:
      - "21:21"       # FTP
      - "80:80"       # HTTP
      - "2222:2222"   # SSH (HoneyPot)
      - "23:23"       # Telnet
      - "3306:3306"   # MySQL
      - "445:445"     # SMB
      - "3389:3389"   # RDP
    networks:
      - azazel_net
  
networks:
  azazel_net:
    driver: bridge
