services:
  vector:
    image: timberio/vector:0.37.0-alpine
    container_name: siem-vector-1
    volumes:
      - ./vector/config/vector.yaml:/etc/vector/vector.yaml:ro
      - ./data:/data
    ports:
      - "6000:6000"
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - siem-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - xpack.security.enabled=false     # ← 認証まるごとオフ
    ports:
      - "9200:9200"
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
    networks:
      - siem-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - ELASTICSEARCH_USERNAME=… （不要）
      # - ELASTICSEARCH_PASSWORD=… （不要）
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - siem-network

networks:
  siem-network:
    driver: bridge