%YAML 1.1
---

# ========================
#  Suricata Configuration
# ========================

vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16]"
    EXTERNAL_NET: "!$HOME_NET"  # 'any' から自ネット以外に変更
    HTTP_SERVERS: "$HOME_NET"
    SSH_SERVERS: "$HOME_NET"
    SQL_SERVERS: "$HOME_NET"
    SMTP_SERVERS: "[192.168.1.0/24]"
    DNS_SERVERS: "[8.8.8.8, 8.8.4.4]"
    TELNET_SERVERS: "$HOME_NET"

  port-groups:
    SHELLCODE_PORTS: "0:1024"
    ORACLE_PORTS: "1521"
    HTTP_PORTS: "80,443"
    SSH_PORTS: "22"
    SQL_PORTS: "5432"


default-rule-path: /var/lib/suricata/rules

rule-files:
  - suricata.rules  # カスタムルールファイル

af-packet:
  - interface: wlan1
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    disable-promisc: no

outputs:
  - fast:
      enabled: yes
      filename: /var/log/suricata/fast.log
      append: yes

  - eve-log:
      enabled: yes
      filetype: regular
      filename: /var/log/suricata/eve.json
      types:
        - alert:
            tagged-packets: yes
        - flow
        - stats

logging:
  default-log-level: info
  outputs:
    - console:
        enabled: no
    - file:
        enabled: yes
        level: info
        filename: /var/log/suricata/suricata.log
        
app-layer:
  protocols:
    dnp3:
      enabled: yes
    modbus:
      enabled: yes

classification-file: /etc/suricata/classification.config
reference-config-file: /etc/suricata/reference.config
